# Generated by Django 2.0.3 on 2018-03-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0012_auto_20180318_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=1000),
        ),
    ]
