# Generated by Django 2.0.3 on 2018-07-05 04:53

import alumni.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0014_temporary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='temporary',
            name='document',
            field=models.FileField(upload_to='Alumni_videos/0', validators=[alumni.validators.file_size]),
        ),
    ]
