# Generated by Django 2.0.3 on 2018-07-12 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0017_auto_20180712_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author_image',
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='home.Person'),
        ),
    ]
