# Generated by Django 2.0.3 on 2018-07-12 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=30)),
                ('roll_no', models.IntegerField(blank=True, default=160123005)),
                ('person_phone_no', models.IntegerField(blank=True, default=9993993287)),
                ('person_img', models.ImageField(default='profile_img/profile.png', upload_to='profile_img')),
                ('person_email_link', models.EmailField(max_length=254, null=True)),
                ('person_fb_link', models.URLField(null=True)),
                ('person_ln_link', models.URLField(null=True)),
                ('person_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
