# Generated by Django 2.0.3 on 2018-03-17 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('roll_no', models.IntegerField(blank=True, default=160123005)),
                ('phone_no', models.IntegerField(blank=True, default=999999999)),
                ('profile_img', models.ImageField(default='profile_img/profile.png', upload_to='profile_img')),
                ('passout_year', models.IntegerField(blank=True, choices=[(1997, '1997'), (1998, '1998'), (1999, '1999'), (2000, '2000'), (2001, '2001'), (2002, '2002'), (2003, '2003'), (2004, '2004'), (2005, '2005'), (2006, '2006'), (2007, '2007'), (2008, '2008'), (2009, '2009'), (2010, '2010'), (2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021')], default=2016)),
                ('email_link', models.EmailField(max_length=254, null=True)),
                ('fb_link', models.URLField(null=True)),
                ('ln_link', models.URLField(null=True)),
                ('curr_work', models.CharField(blank=True, max_length=100)),
                ('prev_work', models.CharField(blank=True, max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
