# Generated by Django 2.0.3 on 2018-03-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='pdf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='video',
            field=models.BooleanField(default=False),
        ),
    ]
