# Generated by Django 2.0.3 on 2018-03-29 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20180326_0353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('semester', models.CharField(choices=[('1', '1st'), ('2', '2nd'), ('3', '3rd'), ('4', '4th'), ('5', '5th'), ('6', '6th'), ('7', '7th'), ('8', '8th')], default=' ', max_length=50)),
                ('subject', models.CharField(choices=[('1', 'Bio'), ('2', 'Cse'), ('3', 'Math'), ('4', 'Me')], default=' ', max_length=50)),
                ('video', models.BooleanField(default=False)),
                ('image', models.BooleanField(default=False)),
                ('pdf', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
