# Generated by Django 2.0.3 on 2018-03-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20180329_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='semester',
            field=models.CharField(choices=[('1', '1st'), ('2nd', '2nd'), ('3', '3rd'), ('4', '4th'), ('5', '5th'), ('6', '6th'), ('7', '7th'), ('8TH', '8th')], default=' ', max_length=50),
        ),
    ]
