# Generated by Django 2.0.3 on 2018-03-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20180329_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='document',
            field=models.FileField(upload_to='student_notes/'),
        ),
    ]
