# Generated by Django 2.0.3 on 2018-03-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_auto_20180329_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='type',
            field=models.CharField(choices=[('', '-------'), ('Before_Midsem_Notes', 'Before_Midsem_Notes'), ('Quiz1_Paper', 'Quiz1_Paper'), ('Midsem_Paper', 'Midsem_Paper'), ('After_Midsem_Notes', 'After_Midsem_Notes'), ('Quiz2_Paper', 'Quiz2_Paper'), ('Endsem_Paper', 'Endsem_paper')], default=' ', max_length=50),
        ),
    ]
