# Generated by Django 2.0.3 on 2018-04-01 17:17

from django.db import migrations, models
import student.validators


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_auto_20180330_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='document',
            field=models.FileField(upload_to='student_notes/', validators=[student.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='note',
            name='subject',
            field=models.CharField(choices=[('', '-------'), ('Bio1', 'Bio1'), ('Cse1', 'Cse1'), ('Math1', 'Math1'), ('Me1', 'Me1'), ('Bio2', 'Bio2'), ('Cse2', 'Cse2'), ('Math2', 'Math2'), ('Me2', 'Me2'), ('Bio3', 'Bio3'), ('Cse3', 'Cse3'), ('Math3', 'Math3'), ('Me3', 'Me3')], default=' ', max_length=50),
        ),
    ]
