# Generated by Django 2.0.3 on 2018-07-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_auto_20180401_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='subject',
            field=models.CharField(choices=[('', '-------'), ('CH101', 'CH101'), ('CH110', 'CH110'), ('MA101', 'MA101'), ('MA102', 'MA102'), ('CS101', 'CS101'), ('EE102', 'EE102'), ('MA201', 'MA201'), ('MA221', 'MA221'), ('MA222', 'MA222'), ('MA224', 'MA224'), ('MA226', 'MA226'), ('CS222', 'CS222'), ('MA322', 'MA322'), ('MA372', 'MA372'), ('MA321', 'MA321'), ('MA351', 'MA351'), ('Competitive_coding', 'Competitive_coding'), ('Machine_learning', 'Machine_learning')], default=' ', max_length=50),
        ),
    ]
